AboutCityGroups.create(id: 1, name: 'Город Заречный и соседи')
AboutCityGroups.create(id: 2, name: 'Градообразующие предприятия')
AboutCityGroups.create(id: 3, name: 'БН-800')
AboutCityGroups.create(id: 4, name: 'Образовательные учреждения')
AboutCityGroups.create(id: 5, name: 'МСЧ-32')
AboutCityGroups.create(id: 6, name: 'Дельтапланерный клуб')
AboutCityGroups.create(id: 7, name: 'Карнавал')
AboutCityGroups.create(id: 8, name: 'Таховский бульвар')
AboutCityGroups.create(id: 9, name: 'Телецентр')
AboutCityGroups.create(id: 10, name: 'Люди')